### ISSUE TITLE
Tut randomly freezes after quiting editor

### ISSUE THREAD

**Issue by maxigaz** [RasmusLindroth/tut#5] opened 2020-05-01 10:26 UTC
Using the fourth version, when I finish composing a post or a reply in Neovim and press `ZZ`, the whole terminal window becomes blank and unresponsive until I run `pkill tut` in another window.

This happens about 20-25% of the time, and I’m not sure how to debug it.

**Comment by RasmusLindroth** [comment] 2020-05-03 16:06
Thank you for the bug report. I can reproduce it, so hopefully I can find a solution soon

**Comment by MegxgeM** [comment] 2020-05-08 01:28
That happens to me practically always I want to compose a toot. Firstly I thought it happened because the number of characters (long texts) but I realized that it happens (it seems) randomly.
I use Vim and (I don't know if this is important but) I already tried it with the terminals Terminator and Alacritty.

**Comment by Leosxe** [comment] 2020-05-24 16:23
This happens to me too, also using Nvim on Linux, it happens almost everytime and it doesn't depend on the number of characters

**Comment by RasmusLindroth** [comment] 2020-05-25 14:46
It's the same for me. I'm still trying to find out why it happens. I thought that it would be easy, but I've still not found out why it happens. But I'll have much more spare time in about two and a half week. Hopefully I have a bug fix in place pretty soon :)

**Comment by RasmusLindroth** [comment] 2020-06-14 13:45
I have still not found a good solution, but tut now sleeps for 100 milliseconds, so hopefully it doesn't crash anymore.

It seems like there might be a bug in tview that's causing it, so I will look at it some more. Here is the related issue https://github.com/rivo/tview/issues/244

**Comment by RasmusLindroth** [comment] 2021-06-29 19:19
This is hopefully solved with some updates to tview and tcell. Open it again if I need to revert back to sleep after closing the editior.

**Closed by RasmusLindroth** 2021-06-29 19:19 UTC
Labels: bug
